### ISSUE TITLE
Error: Unable to encode true of the type boolean

### ISSUE THREAD

**Issue by Rutulpatel7077** [prismicio/prismic-javascript#117]
The document says Boolean is acceptable but It looks like js ( React client or maybe all of them ) does not support  Boolean values with **Predicates.at**.

![image](https://user-images.githubusercontent.com/22271244/74052819-fb745b80-49b0-11ea-86b7-10a72586fd54.png)

**Example**:

`client.query([Prismic.Predicates.at('my.activity.featured', true)])`

**Error**: Unable to encode true of the type boolean

![image](https://user-images.githubusercontent.com/22271244/74160276-880e5c00-4bf3-11ea-8aed-fce632c0cb97.png)
**Documentation Reference**:  https://prismic.io/docs/reactjs/query-the-api/query-predicates-reference

https://github.com/prismicio/prismic-javascript/blob/365b9107cc3a12cf4da0ab824dc45f17735ac30f/src/Predicates.ts#L34

**Comment by Mzem** [comment]
Having the same issue

**Comment by hypervillain** [comment]
Just made a PR about this: #118  ✌️
