### ISSUE TITLE
Querying document fields "function at(..)] unexpected field"

### ISSUE THREAD

**Issue by de-monkeyz** [prismicio/prismic-javascript#12]
Hello,

I've just started using the prismic API to start building a blog on my company's website, however when testing out the API via the documentation, I'm running into an exception from the API.

Whenever I run a query to filter by a specific field for a document type, e.g. `Prismic.Predicates.at('my.blog_post.title', 'Some Title'),`, the API responds with a 400 error in which the error message

```
[function at(..)] unexpected field 'my.blog_post.title' on line:1 col:48 in query '[[:d = at(document.type, &quot;blog_post&quot;)][:d = at(my.blog_post.title, &quot;&quot;)]]''

[[:d = at(document.type, &quot;blog_post&quot;)][:d = at(my.blog_post.title, &quot;&quot;)]]'
```

Is returned to me. This occurs when running any sort of predicate on a custom field, including the `at` and `any` queries, with or without the proceeding document.type query.

I can't see anything that's wrong with my syntax as I've copied examples directly from the docs, here is the full code I'm running for context:

```javascript
const Prismic = require("prismic-javascript");

const getArticle = async function() {
  try {
    const api = await Prismic.getApi("https://xxx.prismic.io/api/v2");
    const result = await api.query([
      Prismic.Predicates.at("document.type", "blog_post"),
      Prismic.Predicates.at('my.blog_post.title', 'Some Title'),
    ], {
      orderings: "[my.blog_post.date desc]",
      fetchLinks: "author.name",
    });

    console.log(JSON.stringify(result, null, 2));

  } catch (e) {
    console.warn(e);
  }
}
getArticle();
```

Any help is greatly appreciated.

**Comment by arnaudlewis** [comment]
@de-monkeyz Your "title" field must be a rich text so you can't use the "at" predicate. You should just use the "fulltext" predicate instead or change it from rich text to key text.

**Comment by de-monkeyz** [comment]
Ah, I see. Thanks very much for the clarification, that seems to have cleared things up.!

**Comment by vuquanghoang** [comment]
I have nested field like this my.company.products.product (products's type is group and there are product inside). I try to search by this string [fulltext(my.company.products.product, "Beer")]. I cannot see any result but I'm sure there 's data in CMS. Any idea?
