### ISSUE TITLE
random FetchErrors when querying the api

### ISSUE THREAD

**Issue by Bergrebell** [prismicio/prismic-javascript#122]
I have the following query to build my routes in nuxtJS. We have quite some pages in our project and while fetching we often get the following errors:

```
FetchError: request to https://OUR-PRISMIC.cdn.prismic.io/api/v2/documents/search?page=1&pageSize=1&ref=[...] failed, reason: socket hang up
```
or

```
FetchError: request to https://climeworkscom.cdn.prismic.io/api/v2/documents/search?page=1[...] failed, reason: read ECONNRESET
```

This is the query. 

```
     const page = initApi().then(api => {
        return api
          .query(Prismic.Predicates.at('document.type', 'page'))
          .then(response => {
            return response.results.map(payload => {
              return `/page/${payload.uid}`
            })
          })
      })
 [...]
    const results = [page, news, events]
      return Promise.all(results).then(values => {
        const allRoutes = []
        values.forEach(value => {
          allRoutes.push(...value)
        })
        return allRoutes
      })

```

Any idea why this happens? And how can we make sure that the requests succeed?

**Comment by Bergrebell** [comment]
turns out i've used an old version of node-fetch. upgrading to `node-fetch@^2.6.0` solved the issue.

**Comment by srenault** [comment]
Hello,

There are no reason it should happen. Could you contact the support so we check the logs on our side?

**Comment by timtyrrell** [comment]
@Bergrebell we have been getting some of those, as well, if you have any insight to share let me know, thanks!

**Comment by Bergrebell** [comment]
@timtyrrell - we moved to heroku (ssr instead of pre-rendered via generate) because of this. but i've found this article by markus oberlehner that seems to solve this issue. you can find it [here](https://markus.oberlehner.net/blog/cut-your-nuxt-generate-build-time-in-half-with-context-payload/).
