### ISSUE TITLE
Inconsistency in types/modules after version 3.0.0

### ISSUE THREAD

**Issue by horttanainen** [prismicio/prismic-javascript#140]
In your 3.0.0 release notes (https://github.com/prismicio/prismic-javascript/releases/tag/3.0.0-beta.0) you state that:

> the module no longer exports named functions and variables. It only exports the Prismic object. So import Prismic from 'prismic-javascript' will work as before, but import * as Prismic from 'prismic-javascript will now fail

However we have found out that exactly the opposite is true. 

1. When we use ` import Prismic from 'prismic-javascript` we get `cannot call method X of undefined` errors, where undefined is the supposedly default exported Prismic. 

2. On the other hand, when we export Prismic exactly as we are not supposed, `import * as Prismic from 'prismic-javascript` everything works as before, but the types are broken. E.g. this works, but requires the @ts-ignore:
```
import * as Prismic from 'prismic-javascript'

// @ts-ignore
Prismic.getApi(apiEndpoint)
```

We are using prismic-javascript 3.0.2

**Comment by lihbr** [comment]
Hey, I'm sorry we failed to give you any attention back then.

Kit has now moved to version 5, upcoming version 6 will also come with first-class TypeScript support 🎉

Have a great week!
