### ISSUE TITLE
Endpoint URL is not constructed properly when using `access_token` and `routes` API options

### ISSUE THREAD

**Issue by lihbr** [prismicio/prismic-javascript#142]
### Version

- Prismic CLI version (know it by running `prismic --version`): 

### Reproduction

1. Init API using both `access_token` and `routes`

### What is expected?

A properly constructed URL: `https://200629-sms-hoy.cdn.prismic.io/api/v2?access_token=MC5YM3hmbWhNQUFDWUFubTlL.J--_ve-_ve-_vWvvv71UO2dXM--_ve-_ve-_vUrvv70xKgrvv73vv73vv71VBz3vv71MHi0777-977-9&routes=%5B%7B%22type%22%3A%22page%22%2C%22path%22%3A%22%2F%3Auid%22%7D%5D` (`?` then `&`)

### What is actually happening?

401 happens because URL is not constructed properly: `https://200629-sms-hoy.cdn.prismic.io/api/v2?access_token=MC5YM3hmbWhNQUFDWUFubTlL.J--_ve-_ve-_vWvvv71UO2dXM--_ve-_ve-_vUrvv70xKgrvv73vv73vv71VBz3vv71MHi0777-977-9?routes=%5B%7B%22type%22%3A%22page%22%2C%22path%22%3A%22%2F%3Auid%22%7D%5D` (2 x `?`)

### Any additionnal information

This is due to the `separator` function being called with argument `url` instead of potential updated one: `this.url`: https://github.com/prismicio/prismic-javascript/blob/v4/src/Api.ts#L29-L35

@arnaudlewis

**Comment by arnaudlewis** [comment]
fixed here: https://github.com/prismicio/prismic-javascript/pull/143/commits/db60da93fbd0dcc61f04a92c856d8d9f92f5cd38
