### ISSUE TITLE
Add guide for generating graphQL schema

### ISSUE THREAD

**Issue by timuric** [prismicio/prismic-javascript#151]
I have spent quite some time figuring out how to generate graphql schema, which turned out to be quite simple but not obvious. Turns out you need to use ```GET``` request and include ```prismic-ref``` header.

You can achieve this with this tool
```https://github.com/dotansimha/graphql-code-generator```

and add parameters in the yaml config:

![image](https://user-images.githubusercontent.com/4006792/104734486-a3a5af00-5740-11eb-8d7c-d96f78001d34.png)

I think its this is quite an essential guide for anyone who wants to have proper IDE experience or works with Typescript.

**Comment by lihbr** [comment]
Hey @timuric, I'm sorry we failed to give your issue attention back then. Thanks for sharing your knowledge on that. I forwarded your issue to our documentation team! Have a great week!
