### ISSUE TITLE
NPM only showing up to version 3.0.2

### ISSUE THREAD

**Issue by neilmispelaar** [prismicio/prismic-javascript#152]
Hello,

NPM is only showing up to version 3.0.2.

Would it be possible to update NPM to have the latest and greatest? 

Thanks so much.

<img width="1344" alt="Screen Shot 2021-02-02 at 1 02 37 PM" src="https://user-images.githubusercontent.com/9325038/106642889-ef38c500-6556-11eb-8d3e-59a1d8caada1.png">

Source: https://www.npmjs.com/package/prismic-javascript

**Comment by lihbr** [comment]
Hey @neilmispelaar, thanks for your contribution!

Indeed we moved Prismic Javascript to [@prismicio/client](https://www.npmjs.com/package/@prismicio/client), you can get the latest and greatest there 🙂

@arnaudlewis, friendly reminder to `$ npm deprecate` the legacy one~

**Comment by neilmispelaar** [comment]
@lihbr 

Thanks so much for the clarification. 

If I may recommend - would it be possible to update the readme file on the prismic-javascript repo to show the correct npm command `npm install @prismicio/client --save` 

<img width="879" alt="Screen Shot 2021-02-03 at 1 30 29 PM" src="https://user-images.githubusercontent.com/9325038/106792332-00033c80-6624-11eb-879d-dbca97544dc2.png">
