### ISSUE TITLE
Deprecation of tags list from /api and /api/v2 endpoints on April 1, 2021

### ISSUE THREAD

**Issue by LennartVandoorne** [prismicio/prismic-javascript#159]
Hi all
Do you believe the deprecation of the tags list from the api/v2 endpoints will result in any breaking changes when using prismic-javascript in a project?

**Comment by lihbr** [comment]
Hey @LennartVandoorne, I'm sorry for the lack of attention your question received back then, usually we provide much quicker support for that kind of questions through our community forum: https://community.prismic.io

To answer your question this should have no impact for your if you weren't using the list of tags that comes from the `/api/v2` endpoint. If you were you'll now have to use the new dedicated endpoint through the new helper: `api.getTags()` (shipped as part of `v5.1`)

Feel free to reopen if anything!
