### ISSUE TITLE
Authorization header not accepted by CDN URL

### ISSUE THREAD

**Issue by angeloashmore** [prismicio/prismic-javascript#168]
If the CDN API URL is used (the recommended practice, enforced by `Client.prototype.getEndpoint`), the `Authorization` header is not accepted to provide an access token.

Currently, only non-CDN URLs support the Authorization header.

**Temporary solution**: Revert to attaching the access token to the `access_token` URL parameter.
**Long-term solution**: Enable the Authorization header on the CDN.

**Comment by lihbr** [comment]
Let's bring that during our meeting next week :)

**Comment by angeloashmore** [comment]
The CDN has been updated to accept the Authorization header. No changes to the library needed!
