### ISSUE TITLE
[v6] `getRefById` capitalization

### ISSUE THREAD

**Issue by samlfair** [prismicio/prismic-javascript#190]
It looks like we're capitalizing acronyms in variable names, but "ID" is not capitalized in `getRefById`. (It is in `getByID` and `getReleasesByID`, so I assume this is a typo.)

In general, I think it would be good to be really consistent about whether we capitalize acronyms in variable names. If users are unsure, it creates annoyance throughout their workflow. (Is it `asHTML` or `asHtml`? `getByUID` or `getByUid`?)

**Comment by lihbr** [comment]
You're right, it should be capitalized ☺️

**Comment by angeloashmore** [comment]
Good catch! Yes, `ID` should be capitalized to be in line with `asHTML`, `URL`, and `UID`.

I've replaced all instances of "Id" with "ID" (https://github.com/prismicio/prismic-javascript/commit/2bcdabf829f309f856b757a3401aacae6856bba4) and will be the standard going forward.

Published in `v6.0.0-alpha.12`
