### ISSUE TITLE
Images with "ß" in their file name result in "403 Forbidden"

### ISSUE THREAD

**Issue by evolkmann** [prismicio/prismic-javascript#25]
When uploading an Image to the Media Library which contains the character `ß` in its file name, the image can not be loaded properly.

Repository-Privacy settings do not affect the issue.

Example response when loading the image from S3:
```
<?xml version="1.0" encoding="UTF-8"?>
<Error>
    <Code>AccessDenied</Code>
    <Message>Access Denied</Message>
    <RequestId>ED58F636AF35D6AA</RequestId>
    <HostId>WxVXqhP+1mTWGa/4QkwJur5fNGThGtr2GlCY1y/xgRsphRgKnXsSVY+GDHPQ9hyEuxsdJ9huiqQ</HostId>
</Error>
```

*Steps to reproduce*:
- Upload image file with "ß" in file name
- Create a content object containing the image
- Try to load it via the provided S3-URL

**Comment by levimykel** [comment]
Hello,

Sorry for the delayed response. Can you submit this issue on the online chat support on the prismic.io website? This is an issue with prismic, not with this kit.

Thanks,
Levi
