### ISSUE TITLE
Type error preventing google closure advanced compilation.

### ISSUE THREAD

**Issue by madstap** [prismicio/prismic-javascript#26]
There is a type issue that prevents the google closure compiler from knowing that it can't re-write the `"Accept"` in `request.ts`. I'm pretty sure it is related to this error, which can be seen by running `tsc` in the project root.

```
src/request.ts(43,24): error TS2352: Type '{ headers: { Accept: string; }; }' cannot be converted to type 'NodeRequestInit'.
  Types of property 'headers' are incompatible.
    Type '{ Accept: string; }' is not comparable to type 'Headers | string[][] | undefined'.
      Type '{ Accept: string; }' is not comparable to type 'string[][]'.
        Property 'length' is missing in type '{ Accept: string; }'.
```

**Comment by levimykel** [comment]
Hi @madstap,
Sorry for the delayed response. I had no trouble running this through the google closer compiler. Which version of the prismic-javascript are you attempting to compile?

**Comment by srenault** [comment]
Since we have no answer, I close this issue.
