### ISSUE TITLE
require('prismic-javascript') instead of require('prismic-javascript').default

### ISSUE THREAD

**Issue by bulby97** [prismicio/prismic-javascript#3]
Just went through an issue setting up the lib. 
Following the README, it's not possible to make the lib work.
I noticed that in your demo you use `require('prismic-javascript').default` because of the way TS exports in ES6. 

Is it possible to fix this issue ? Or else change the README

**Comment by arnaudlewis** [comment]
@bulby97 
It's fixed in 1.0.5 here: https://github.com/prismicio/prismic-javascript/tree/v1.0.5
