### ISSUE TITLE
Add a Uid/Slug field when creating new slice

### ISSUE THREAD

**Issue by pxwee5** [prismicio/prismic-javascript#31]
Please add a Uid or Slug field for each slices in the beta builder. The slug should set the object name in the JSON object. 

At the moment there is no way other than manually change the JSON object name. 

![image](https://user-images.githubusercontent.com/14123790/34926028-c2136b88-fa11-11e7-8d4d-a52b4b7294b4.png)

**Comment by levimykel** [comment]
Hi @pxwee5,
Please submit this issue via the chat support on the prismic.io website. This is an issue with the prismic.io platform, not this development kit. Thanks!
