### ISSUE TITLE
Ability to create a standard component using JSON

### ISSUE THREAD

**Issue by pxwee5** [prismicio/prismic-javascript#32]
Right now I am adding labels to all my RichText editors 
```
labels: ["blockquote"]
```
But because we cannot save it as a custom component, I'll have to manually add the same code above to all the RichText JSON object. 

Any idea if this is in the roadmap or not?

**Comment by levimykel** [comment]
Hi @pxwee5,
Please submit these types of inquiries in the online chat support on the prismic.io website. The issues posted here should be specific to issues with this kit. Thanks for your understanding!
