### ISSUE TITLE
Queries keep timing out

### ISSUE THREAD

**Issue by kelvinlouis** [prismicio/prismic-javascript#44]
Hey there,

For some reason and quite often our calls to the API fail with a ETIMEDOUT. The application runs on a Azure Web App using node-iis. Depending on the resource, a lot of concurrent queries can occur, as we are trying to fetch nested references (imagine a navigation) or a slice that references a different resource.

Here are some examples of the errors:
```
(node:5748) UnhandledPromiseRejectionWarning: FetchError: request to https://xxx.cdn.prismic.io/api/v2 failed, reason: connect ETIMEDOUT 54.192.27.125:443
    at ClientRequest.<anonymous> (D:\home\site\wwwroot\node_modules\node-fetch\index.js:133:11)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

or

```
(node:5748) UnhandledPromiseRejectionWarning: FetchError: request to https://xxx.cdn.prismic.io/api/v2/documents/search?page=1&pageSize=100&lang=it-ch&ref=....&q=%5B%5Bany(document.type%2C%20%5B%22default_page%22%2C%22empty_page%22%2C%22communities_page%22%2C%22home_page%22%2C%22ranking_page%22%2C%22sponsors_page%22%5D)%5D%5D failed, reason: connect ETIMEDOUT 54.192.27.125:443
    at ClientRequest.<anonymous> (D:\home\site\wwwroot\node_modules\node-fetch\index.js:133:11)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

These are just some examples and I wasn't able to reproduce them. For every incoming request we initialize the API and reuse that API throughout the request.

Do you have any ideas what could cause this problem? Is there something I can do? Is it possible to set a keep alive agent for the requests to your API?

I am interested to see what you guys think. I haven't found any way yet, to resolve this issue.

**Comment by seaneking** [comment]
I'm seeing this too, did anyone find out what's going on, or a potential fix? For me it started when the resource I was requesting (documents with a certain type) exceeded around 25 items.

**Comment by hypervillain** [comment]
Hey @seaneking, are you behind a proxy by any chance ([http://amibehindaproxy.com](http://amibehindaproxy.com))?

Today is my support day 👉 message us on Intercom with your repository name and I'll bother the right people for this issue

**Comment by hypervillain** [comment]
In the meantime, this could help you: https://stackoverflow.com/questions/24320578/node-js-get-request-etimedout-esockettimedout

**Comment by dimitrinicolas** [comment]
I a having the same issue for a few days. It happens randomly on both API requests and Prismic CDN resources fetching. I am using [angeloashmore/gatsby-source-prismic](https://github.com/angeloashmore/gatsby-source-prismic).

**Comment by seaneking** [comment]
Ditto, not behind a proxy.

**Comment by dimitrinicolas** [comment]
I figured out how to fix my issue by setting a `maxSockets` option to `100` to the http request agent.

Example:

```js
const client = await Prismic.api(apiEndpoint, {
  accessToken,
  proxyAgent: new require('https').Agent({ maxSockets: 100 })
});
```

**Comment by alexander-fischer** [comment]
I tried the solution of @dimitrinicolas but it didn't work. Are there any updates on this issue?

**Comment by dimitrinicolas** [comment]
@alexander-fischer I'm sorry, I'm even no longer using the proxyAgent and I had no issue since few months. I have no more idea for this problem, the Prismic team didn't know anything about any change on their API when I contacted them.

**Comment by arnaudlewis** [comment]
This shouldn't happen by default because we rely on the default implementation of the HttpAgent that allows you to have enough opened connection.
If you use a proxy and need to implement your own HttpAgent, you need to setup enough sockets and use the keepalive option to keep to connection open if you have a lot of concurrent calls.
```
const httpAgent = new HttpAgent({		
   keepAlive: true,		
   maxSockets: 20,		
 });
```
It would look like this
