### ISSUE TITLE
Request pending

### ISSUE THREAD

**Issue by DCKT** [prismicio/prismic-javascript#5]
Hello,

I'm trying this module for the API v2 but when I try to call `api.getByUID`, the request is blocked on pending.

I think the API v2 is enabled on my repo because we can [reach this url](https://testcolisweb.cdn.prismic.io/api/v2) .

I tried the Node.js demo by replacing the endpoint to mine, I got the same result.

Have you got an idea about this ? 

Thanks for your help.

**Comment by arnaudlewis** [comment]
@DCKT I tried to reach this route but it's a 404, your repo probably doesn't have the v2 activated.
