### ISSUE TITLE
set timeout

### ISSUE THREAD

**Issue by zjhou** [prismicio/prismic-javascript#55]
Hi,
Sometimes, data query takes too long, how can i set a timeout value ?

**Comment by srenault** [comment]
Hello, 

I'm curious, what would you do in your website if you reach the timeout? 

Behind the scene we use fetch to perform the query and it doesn't provide built-in way to set timeout. We could do it by using a setTimeout that would resolve the promise after a timeout.
By the way you can still do it on your side. What do you think? I'm not sure if we have to provide it in this library.

**Comment by arnaudlewis** [comment]
I guess using Promise.race(https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/race) would be an elegant way to solve this.
That would be a great addition to the library but it can still be implemented outside of the library.
