### ISSUE TITLE
Preview document on node server not working

### ISSUE THREAD

**Issue by klase** [prismicio/prismic-javascript#63]
When making api calls (using prismic-javacript) on our node server we always get the latest published document instead of the draft one. If I log the cookies I can see that we have the "io.prismic.preview" cookie on the node side just before the api call is made but the returned document is always the published one. Running the same code on the client works fine however.

**Comment by Duaner** [comment]
Hello @klase we created documentation on how to trouble shoot this. https://user-guides.prismic.io/en/articles/3403530-trouble-shooting-previews

You should be sure that you pass the req in your request to make it work. 

Closing this issue.
