### ISSUE TITLE
Shared cache

### ISSUE THREAD

**Issue by tpbowden** [prismicio/prismic-javascript#67]
My express server requests a lot of content from prismic which doesn’t change very often. Is it possible to share the cache between individual requests? I want to still be able to pass the req object into a new prismic client on each request to ensure preview and experiments keep working as expected

**Comment by srenault** [comment]
Hello @tpbowden,

This library is provided with a default cache implementation (in-memory). FYI, you can specify your own implementation (that would be redis, memcached...).
