### ISSUE TITLE
API values not in camelcase

### ISSUE THREAD

**Issue by augustinusbader** [prismicio/prismic-javascript#68]
Values returned from the API are not in camelcase. Expected `myTitleField` to be returned but instead received my_title_field. This becomes an issue when working with ESlint as I have to fully disable the `camelcase` rule. Assuming there is no option of changing/ editing how data comes back from the API?

**Comment by arnaudlewis** [comment]
No there is none. the underscore formatting is more standard in APIs. the camelCase is a good convention for code and eventually JS API but _ was decided and we cannot change the format for compatibility reason.
