### ISSUE TITLE
Predicates.at doesn't allow arrays

### ISSUE THREAD

**Issue by sventschui** [prismicio/prismic-javascript#7]
It is currently not possible to supply an array to `Predicates.at` (e.g. `Predicates.at('document.tags', ["foo", "bar"])` because there are hardcoded `"` in https://github.com/prismicio/prismic-javascript/blob/master/src/predicates.ts#L33

**Comment by arnaudlewis** [comment]
thanks for that report @sventschui, it's fixed in v1.1.4.
