### ISSUE TITLE
2.0 is published to NPM but has no changelog

### ISSUE THREAD

**Issue by emirotin** [prismicio/prismic-javascript#75]
So the question is: what are the breaking changes there?

**Comment by srenault** [comment]
Hello @emirotin ,

I just updated the changelog (https://github.com/prismicio/prismic-javascript/releases/tag/v2.0.0). The breaking change is comming from ths PR: https://github.com/prismicio/prismic-javascript/pull/71/files

**Comment by emirotin** [comment]
Thanks, that answers my question.
