### ISSUE TITLE
Unable to encode .... of type object - Prismic.Predicate.at()

### ISSUE THREAD

**Issue by joZephhh** [prismicio/prismic-javascript#77]
Hello, 

I've tried to use multiple predicates on a query as [the example](https://prismic.io/docs/javascript/query-the-api/use-multiple-predicates) but when the code (see below) is executed I got an error: Unable to encode no-case-study of type object

```js
const noCasesStudiesProjects = client().then(api => {
    return api
      .query([
        Prismic.Predicates.at('document.type', 'project'),
        Prismic.Predicates.at('document.tags', ['no-case-study'])
      ])
      .then(data => {
        return data.results;
      });
  });
```

I'm using : Nuxt 2.0.0 and prismic-javascript ^2.0.1

Any ideas ? 
Thanks

NB : Until yesterday, everything worked well :/ 
NB2 : Seems to works in build and generate (nuxt) process 🧐

**Comment by mcrider** [comment]
Also unable to run fulltext search queries, getting similar errors. I've tried to build a non-minified prismic-javascript locally so i can debug it, but getting the following error when i run `npm run dev`..  Any help would be greatly appreciated, really need to get these predicate queries working.

```
ERROR in ./src/index.ts 7:10
Module parse failed: Unexpected token (7:10)
You may need an appropriate loader to handle this file type.
| import ResolvedApi, { EXPERIMENT_COOKIE, PREVIEW_COOKIE } from './ResolvedApi';
|
> namespace Prismic {
|
|   export const experimentCookie = EXPERIMENT_COOKIE;
 @ multi promise-polyfill/src/polyfill cross-fetch/polyfill ./src/index.ts main[2]
```

**Comment by mcrider** [comment]
Okay got a non-minified version of prismic-javascript library so i could debug it, looks like this comes down to this line: https://github.com/prismicio/prismic-javascript/blob/edd2c5b66926492dfabd0371100d9f2bc6b413c4/src/Predicates.ts#L41

Due to some awesome javascript idiosyncrasies, which may be dependent on the version of Node being used, instanceof won't work here. Dropped in some logging, hope you find it as fascinating as I do :P

```
  console.log(value); // [ 'articles', 'videos' ]
  console.log(typeof value); // object
  console.log(value instanceof Array); // false
  console.log(Array.isArray(value)); // true
  console.log(Object.prototype.toString.call(value)); // [object Array]
```

Can we switch to use one of the last two methods to test if its an array? Both fix the issue. @arnaudlewis ?

**Comment by kekkorider** [comment]
Any updates on this? this problem is really annoying :/

**Comment by typewriter-software** [comment]
@kekkorider I used the `patch-package` npm package to bypass this bug. Prismic doesn't want to seem to address it. Let me know and I can post the patch I'm using.

**Comment by funkeeflow** [comment]
any new on this? this is really annoying ...

**Comment by mcrider** [comment]
Ran into this again on another project, for those still experiencing it here is a patch you can use with the `patch-package` package: https://gist.github.com/typewriter-software/0fa1e8fa62b4101ceab1ebc421ecb421

- Download this patch file to a `/patches/` directory in the root of your project
- Install `patch-package` from npm
- Add `"postinstall": "patch-package"` to your package.json's scripts object
- Run `npm run postinstall`

**Comment by Atinux** [comment]
Thank you so much @mcrider for finding a workaround.

**Comment by raphaelaitelalim** [comment]
Hey @Atinux, i've updated prismic-javascript and checked in files of the package and i have the latest commit, but still doesn't work...

Any idea ? 
`await Prismic.getApi(prismicConfig.apiEndpoint).then((api) => {
        api.query(
          Prismic.Predicates.any('document.type', ['page', 'serie'])
        ).then(function(response) {
          document = response.results
        })
      });`

I'm getting this error : 
`Unable to encode page,serie of type object`

Thanks 🙏

**Comment by srenault** [comment]
I close that issue since a PR fixed it.
