### ISSUE TITLE
api.getByIDs return 400 HTTP code

### ISSUE THREAD

**Issue by johannpinson** [prismicio/prismic-javascript#8]
Hi,

I use the `getByIDs` query helper for get some content, but the API return an 400.
```
{
  "name": "prismic-request-error",
  "message": "Unexpected status code [400] on URL https://my-awesome-repository.prismic.io/api/v2/documents/search?page=1&pageSize=3&lang=*&ref=PAGEID&q=%5B%5B%3Ad%20%3D%20in(document.id%2C%20%5BXXXX%2CYYYY%5D)%5D%5D",
  "status": 400
}
```

This is the return of api
```
{
  "message": "`]' expected but `[' found on line:1 col:2 in query '[[:d = in(document.id, [XXXX,YYYY])]]'\n[[:d = in(document.id, [XXXX,YYYY])]]\n ^\n",
  "type": "parsing-error",
  "line": 1,
  "column": 2,
  "id": 0,
  "location": "query"
}
```
The bug seems to be about the code, because I can make two separate calls with `getByID`.

I think the bug is about this line :
https://github.com/prismicio/prismic-javascript/blob/master/src/api.ts#L626

And maybe about the predicates function :
https://github.com/prismicio/prismic-javascript/blob/master/src/predicates.ts#L52

(the ids are replaced by `XXXX`and `YYYY` in code)

cc: @Duaner

**Comment by arnaudlewis** [comment]
thanks for that report @johannpinson, it's fixed in v1.1.4.
