### ISSUE TITLE
Random 404 Error

### ISSUE THREAD

**Issue by umxr** [prismicio/prismic-javascript#81]
Decided to work on my app today and got this...
I can still fetch the data fine which confuses me even more
<img width="572" alt="Screenshot 2019-03-10 at 21 11 16" src="https://user-images.githubusercontent.com/20203468/54091715-10003c00-437b-11e9-96d3-c8321ae46b99.png">

**Comment by rayzru** [comment]
Can you please provide information about that issue you had? Did you solve that?
