### ISSUE TITLE
api.getByUID returns unexpected 400

### ISSUE THREAD

**Issue by alexander-fischer** [prismicio/prismic-javascript#82]
Hey,
I use the function: `api.getByUID(type, uid)`and get the following crash message:

`Unexpected status code [400] on URL [...] (my.text-content.uid%2C%20%22kontakt%22)%5D%5D`

UID and type are defined on prismic, I double-checked.

Cheers,
Alex

**Comment by alexander-fischer** [comment]
I found the issue in the naming of the type. But the error response should be improved.

**Comment by MrToxy** [comment]
Having the exact same issue. what do you mean by "found the issue in the naming of the type." how did you solve this, what did you change?

**Comment by alexander-fischer** [comment]
@MrToxy sorry for my bad answer. The problem was with the name of the type. I think there were some special characters that could not be used. But I can't find any commit, what I fixed exactly. I hope this helps you.

**Comment by marclemagne** [comment]
For the next weary traveler: it is looking for the API ID—so if your custom type is named "Bar" you would want to send `bar`. The type definition for the first argument is `type: string` which is a little confusing.

```
api.getByUID("bar", "some-unique-id", {})
```

(Don't forget to add the options argument which is not optional in the type definitions.)
