### ISSUE TITLE
CORS issue on chrome

### ISSUE THREAD

**Issue by nealoke** [prismicio/prismic-javascript#83]
Hi, we are using the prismic platform to supply our application with content. This content also has 3D images which we need to load in a react component. However when we try this we always get the CORS error:

`Access to fetch at 'https://sales-tool-vdv-antwerpen.cdn.prismic.io/sales-tool-vdv-antwerpen/d19dd7e73958894738b4ae422d02a0d8ab3d2e79_n1-balkon-naar-receptie.jpg' from origin 'https://playground.codecliff.be' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
`

This while when we use the url inside an ´a´ tag it is fine and loads fine. Only when we try to use it in another component which calls the URL I guess it doesn't work.

This issue only shows on chrome (not on safari, edge or firefox) which makes it very critical. For now we are looking into working with a proxy but to be honest it should be possible to add a ´Access-Control-Allow-Origin´ header to the response of those assets.

**Comment by sndrgb** [comment]
I have CORS problems with prismic on two projects (always images loaded for webgl). Ask to prismic support too, but always the same.

**Comment by srenault** [comment]
Hello @sndrgb  @nealoke , We did some updates on our side. Do you still have CORS issues?

**Comment by siasjustin** [comment]
yes, i am having this issue

**Comment by lucashfreitas** [comment]
+1 Same issue here, just on chrome
