### ISSUE TITLE
Ordering when use Predicates.any

### ISSUE THREAD

**Issue by raphaelnoguier** [prismicio/prismic-javascript#85]
I was wondering if we could sort the results of several types :
`Prismic.Predicates.any('document.type', ['page', 'serie'], { orderings : '[my.serie.rank]' })`

I don't get any results with this...

Thanks 🙏

**Comment by rayzru** [comment]
The design doesn't allow you to cross predicates with custom different types. You have to select in between:
- select all the data and then organize/filter it on a client-side
- select separately each type with desired predicates
- use graphQL API that allows you to group request

**Comment by srenault** [comment]
Hello @raphaelnoguier ,
In fact you should able to do that. 
Could you give me a concrete request where you have that issue?

**Comment by srenault** [comment]
Closing it since no answers. Feel free to reopen it.
