### ISSUE TITLE
Content Relationship and Multi-languages: Wrong type for custom types

### ISSUE THREAD

**Issue by maersu** [prismicio/prismic-javascript#86]
Setup: 
* "prismic-javascript": "^1.1.5",
* Two custom types (`home_page` and `tip`). `tip` is used in a slice of `home_page`
* Master language is `de-ch` and a 2nd language `fr-ch`

If I query the master language the custom types in `slice.items` is correct (`"type": "tip",`)

JS:
```
  const client = await Prismic.api(`https://${repositoryName}.prismic.io/api/v2`, { accessToken })
  const response = await client.query("", {lang: "de-ch"})
```

Result
```
{
  "id": "XKXobhAAAJmVNCNu",
  "type": "home_page",
  "lang": "de-ch",
  "data": {
     ...
    "body": [
      {
        "slice_type": "content",
        "items": [
          {
            "tip": {
              "id": "XKbxCxMAACIAP_bb",
              "type": "tip",
              "lang": "de-ch"
            }
          }
        ]
      }
    ]
  }
}

```

But when I query a non-master language I get `"type": "home_page",` as type for the custom type

JS:
```
  const client = await Prismic.api(`https://${repositoryName}.prismic.io/api/v2`, { accessToken })
  const response = await client.query("", {lang: "fr-ch"})
```
Result
```
    {
      "id": "XKXzwxAAAByKNFXn",
      "type": "home_page",
      "lang": "fr-ch",
      "data": {
       ...
        "body": [
          {
            "slice_type": "content",
            "slice_label": null,
            "items": [
              {
                "tip": {
                  "type": "home_page",
                  "lang": "fr-ch",
                 }
              }
            ]}
        ]
      }
    },
```

Any idea why?

Thanks!

**Comment by maersu** [comment]
Actually it looks like its a general problem of the API. I did a dummy repo to test.

While the master language returns the right (`chi`) type for results.[type="paren"]. data.child.type the 2nd language does not.

* master language: https://content-type-test.prismic.io/api/v2/documents/search?ref=XKd5ThMAAPwpQlHb#format=json
* 2nd Language: https://content-type-test.prismic.io/api/v2/documents/search?ref=XKd5ThMAAPwpQlHb&lang=de-ch#format=json

**Comment by arnaudlewis** [comment]
The issue was identified and it's related to the translation from one
locale to another.
We already released a fix to prevent that from happening again and another
fix will be released on Monday for already corrupted links.
Sorry for the inconvenience.

Le ven. 5 avr. 2019 à 18:07, Marcel Eyer <notifications@github.com> a
écrit :

**Comment by maersu** [comment]
Thanks for the answer! Looking forward for the fix!

**Comment by maersu** [comment]
@arnaudlewis it works with a new created repo! Thanks!

**Comment by maersu** [comment]
Hi @arnaudlewis 

There is still similar bug with i18n and custom types. Looks like its related to the _Single Type_ custom type:

master language: https://broken-content.prismic.io/api/v1/documents/search?ref=XKsVyRMAAEqPUjE1#format=json
```
oah: {
  type: "Link.document"
  value: {
  document: {
    id: "XKsRthMAAO6UUh79"
    type: "child"
    tags: [ ]
    lang: "en-us"
    slug: "child-title-en"
}
```

2nd language (document object is missing): https://broken-content.prismic.io/api/v1/documents/search?ref=XKsVyRMAAEqPUjE1&lang=de-ch#format=json
```
{
oah: {
  type: "Link.document"
  value: "=&=033XKsR0hMAAO6UUh96%%parent-single%%"
  }
}
```

Or do I something wrong?

**Comment by arnaudlewis** [comment]
The fix is coming today to resolve this issue.
I'll keepyou posted ;)

Le lun. 8 avr. 2019 à 11:46, Marcel Eyer <notifications@github.com> a
écrit :

**Comment by arnaudlewis** [comment]
The fix was released.
