### ISSUE TITLE
Request handling on this client is a bit absurd

### ISSUE THREAD

**Issue by TomasRup** [prismicio/prismic-javascript#88]
Guys, the way connections are handled looks a bit overengineered and moreover gives false alarms to the users:

1) looking at https://github.com/prismicio/prismic-javascript/blob/master/src/request.ts#L53 what happens if max connections are reached, we timeout in prod. And it's very hard to trace why did we timeout with this implementation. Why to make our node servers spend resources on holding the http(s) connection if you timeout? Just call `callback` with a verbose error. Now it's neither clear no performant

2) The `MAX_CONNECTIONS` set to 20 means that if we have one server, we cannot exceed ~60 users/minute. Then we either need to cache everything (then your cms is no longer instant) or we need to increase the amount of server. This should work ok with some little websites, but if we have a huge load, this doesn't work.

3) I'm not sure if there's a reason to have https://github.com/prismicio/prismic-javascript/blob/master/src/request.ts so complex? I.e. request is processed only at the time of queueing and etc. I don't think it's the best way to fix issue of too many requests spamming to your server, that's not client's thing. Why to have this queue implementation?

So to work around this, now I have 12 node instances and forked this repo to increase max connections to 100, to be able to withhold users at peaks times. But I think this is a bit absurd solution and your client library should be changed.

If you agree, maybe I could create a PR.

Don't you agree?

**Comment by arnaudlewis** [comment]
Hi @TomasRup,

I think even on client side it makes sense to have some kind of limit to prevent your client to run an infinite load of queries.
But you do have a point and I'd be happy if you could make a PR with a clean implementation that could really improve this mechanism which is complex, I agree on this.

**Comment by arnaudlewis** [comment]
Hi @TomasRup,

Do you have any progress on this?
I'd be happy to help you on this one so we can offer a smooth experience and prevent the timeout issue with the kit.

**Comment by MarcMcIntosh** [comment]
Hi @TomasRup 

Can you try creating a http.Agent with the keepAlive option set to true and  pass it as proxyAgent option to the Prismic instance?

Something like this
```js
const http = require('http');

const Agent = new http.Agent({ keepAlive: true });

Prismic.client("http://example.prismic.io", { 
  proxyAgent: Agent,
});
```
And let me know if that helps?

Thanks

Marc

**Comment by arnaudlewis** [comment]
@TomasRup This issue is fixed in version 2.1.0 thanks to @MarcMcIntosh.

**Comment by TomasRup** [comment]
Awesome, thanks. Sorry I was on vacation, didn't help 😄

**Comment by MarcMcIntosh** [comment]
@TomasRup upgrade to the most recent version :)
