### ISSUE TITLE
The "options.agent" property must be one of type Agent-like Object, undefined, or false. Received type function

### ISSUE THREAD

**Issue by adam404** [prismicio/prismic-javascript#92]
During a current gatsby build with version 2.1.0 as of today.

prismic-javascript version: 2.1.0
node version: v10.3.0
gatsby-source-prismic-graphql: 3.3.1

**Build Error:**
The "options.agent" property must be one of type Agent-like Object, undefined, or false. Received type function

Seems related to recent agent updates merged today which is setting agent to a function and some strict type checking.

`  fetchOptions.agent = changeAgent;`

`function changeAgent(parsedUrl: any) {
  return (parsedUrl.protocol === 'http:') ? httpAgent : httpsAgent;
}`

**Comment by jamespegg** [comment]
Same here, reverting back to v2.0.3 fixes it.

**Comment by azigler** [comment]
Also having the same problem! Like @adam404 said, it's a type checking issue with the new http/https handling. Not my wheelhouse, but it's unclear if changeAgent is getting passed parsedUrl, which is why it's providing a function as a value instead of the result of the function.

**Comment by samburgers** [comment]
This is also breaking things over here, cheers https://github.com/birkir/gatsby-source-prismic-graphql/issues/58

**Comment by arnaudlewis** [comment]
We just released a patch `2.1.1` that fixes the issue. 
It was related to our conditional `agent` that was not supported by the version on cross-fetch.
We updated that dependency so you are able to do so but removed the implementation by default so you won't have any limit their.
Sorry for the inconvenience.
