### ISSUE TITLE
Massive bundle size increase between 2.0.3 and 2.1.0

### ISSUE THREAD

**Issue by tpbowden** [prismicio/prismic-javascript#93]
The size of the minified production build goes from ~7kb to ~30kb gzipped between 2.0.3 and 2.1.0. Haven't had time to look into what was added, but is there a reason for this increase?

https://bundlephobia.com/result?p=prismic-javascript@2.1.0

**Comment by MarcMcIntosh** [comment]
@tpbowden Thanks for pointing this out :)

**Comment by arnaudlewis** [comment]
Hi @tpbowden , we just released a patch `2.1.1` that will fix the issue. sorry for the inconvenience.

**Comment by tpbowden** [comment]
Great, thanks for the quick turnaround!
